services:
  redis:
    image: redis-local
    container_name: presence-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: presence
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - TOKEN=${TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/.venv
    stdin_open: true
    tty: true

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
